### ISSUE TITLE
Installation error with python 3.9

### ISSUE THREAD

**Issue by michaeldeistler** [sbi-benchmark/diffeqtorch#1]
The following installation fails, but it works with python 3.8. My julia version is 1.5.2.
```
conda create -n multicompartment python=3.9
cd diffeqtorch
pip install -e ".[dev]"
export JULIA_SYSIMAGE_DIFFEQTORCH="$HOME/.julia_sysimage_diffeqtorch.so"
python -c "from diffeqtorch.install import install_and_test; install_and_test()"
```

Traceback:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/michael/Documents/diffeqtorch/diffeqtorch/install.py", line 19, in install_and_test
    test_pyjulia()
  File "/home/michael/Documents/diffeqtorch/diffeqtorch/install.py", line 64, in test_pyjulia
    julia = Julia(compiled_modules=False, debug=True)
  File "/home/michael/anaconda3/envs/multicompartment/lib/python3.9/site-packages/julia/core.py", line 503, in __init__
    self._call(IMPORT_PYCALL)
  File "/home/michael/anaconda3/envs/multicompartment/lib/python3.9/site-packages/julia/core.py", line 538, in _call
    self.check_exception(src)
  File "/home/michael/anaconda3/envs/multicompartment/lib/python3.9/site-packages/julia/core.py", line 587, in check_exception
    raise JuliaError(u'Exception \'{}\' occurred while calling julia code:\n{}'
julia.core.JuliaError: Exception 'LoadError' occurred while calling julia code:
const PyCall = Base.require(Base.PkgId(Base.UUID("438e738f-606a-5dbb-bf0a-cddfbfd45ab0"), "PyCall"))
```

**Comment by michaeldeistler** [comment]
Full installation log:
```
Install PyJulia
[ Info: Julia version info
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
      Ubuntu 19.10
  uname: Linux 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64
  CPU: AMD Ryzen Threadripper 1920X 12-Core Processor: 
                 speed         user         nice          sys         idle          irq
       #1-24  1887 MHz  846670441 s    1808393 s   30214693 s  7014585225 s          0 s
       
  Memory: 62.736881256103516 GB (11923.42578125 MB free)
  Uptime: 3.293332e6 sec
  Load Avg:  1.41845703125  1.18359375  1.12255859375
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
Environment:
  JULIA_SYSIMAGE_DIFFEQTORCH = /home/michael/.julia_sysimage_diffeqtorch.so
  JULIA_PROJECT = /home/michael/Documents/diffeqtorch/diffeqtorch/julia
  HOME = /home/michael
  TERM = xterm-256color
  PATH = /home/michael/.local/bin:/home/michael/anaconda3/envs/multicompartment/bin:/home/michael/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[ Info: Julia executable: /opt/julia-1.5.2/bin/julia
[ Info: Trying to import PyCall...
┌ Warning: PyCall is already installed.  However, you may have trouble using
│ this Python executable because it is statically linked to libpython.
│ 
│ For more information, see:
│     https://pyjulia.readthedocs.io/en/latest/troubleshooting.html
│ 
│ Python executable:
│     /home/michael/anaconda3/envs/multicompartment/bin/python
│ Julia executable:
│     /opt/julia-1.5.2/bin/julia
└ @ Main ~/anaconda3/envs/multicompartment/lib/python3.9/site-packages/julia/install.jl:90
Test PyJulia
DEBUG (28888) 
DEBUG (28888) Debug-level logging is enabled for PyJulia.
DEBUG (28888) PyJulia version: 0.5.6
DEBUG (28888) 
DEBUG (28888) pyprogramname = /home/michael/anaconda3/envs/diff_stats/bin/python
DEBUG (28888) sys.executable = /home/michael/anaconda3/envs/multicompartment/bin/python
DEBUG (28888) bindir = /opt/julia-1.5.2/bin
DEBUG (28888) libjulia_path = /opt/julia-1.5.2/bin/../lib/libjulia.so.1
DEBUG (28888) py_libpython = None
DEBUG (28888) jl_libpython = /home/michael/anaconda3/envs/diff_stats/lib/libpython3.9.so.1.0
DEBUG (28888) is_compatible_python = False
DEBUG (28888) compiled_modules = 'no'
DEBUG (28888) argv_list = [b'/home/michael/anaconda3/envs/multicompartment/bin/python', b'--compiled-modules', b'no']
DEBUG (28888) argc = c_int(3)
DEBUG (28888) jl_parse_opts called
DEBUG (28888) argc = c_int(0)
DEBUG (28888) calling jl_init_with_image(/opt/julia-1.5.2/bin, /opt/julia-1.5.2/lib/julia/sys.so)
DEBUG (28888) seems to work...
DEBUG (28888) exception occured? 140191496175344
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/michael/Documents/diffeqtorch/diffeqtorch/install.py", line 19, in install_and_test
    test_pyjulia()
  File "/home/michael/Documents/diffeqtorch/diffeqtorch/install.py", line 64, in test_pyjulia
    julia = Julia(compiled_modules=False, debug=True)
  File "/home/michael/anaconda3/envs/multicompartment/lib/python3.9/site-packages/julia/core.py", line 503, in __init__
    self._call(IMPORT_PYCALL)
  File "/home/michael/anaconda3/envs/multicompartment/lib/python3.9/site-packages/julia/core.py", line 538, in _call
    self.check_exception(src)
  File "/home/michael/anaconda3/envs/multicompartment/lib/python3.9/site-packages/julia/core.py", line 587, in check_exception
    raise JuliaError(u'Exception \'{}\' occurred while calling julia code:\n{}'
julia.core.JuliaError: Exception 'LoadError' occurred while calling julia code:
const PyCall = Base.require(Base.PkgId(Base.UUID("438e738f-606a-5dbb-bf0a-cddfbfd45ab0"), "PyCall"))
```

**Comment by jan-matthis** [comment]
Thanks for reporting this. I suspect that this has to do with PyJulia in combination with Python 3.9 but not 100% sure of it yet. As a temporary solution I'm thinking of restricting Python to < 3.9 as done in #2. 

For a moment, I thought that the issue might perhaps be fixed by using Julia v1.6.0, but currently there is still this: https://github.com/JuliaPy/pyjulia/issues/437

Edit: The temporary fix is implemented in [version 1.0.1](https://github.com/sbi-benchmark/diffeqtorch/releases/tag/v1.0.1)

**Comment by bkmi** [comment]
I was getting this error with version 1.0.0 and python 3.8 and several versions of Julia. Based off my searches, it is due to the same issues that you've cited. They seem to be fixing it in an upcoming pull request.
