### ISSUE TITLE
Sysimage failure with Julia 1.6

### ISSUE THREAD

**Issue by bkmi** [sbi-benchmark/diffeqtorch#3]
Running the installation seems to cause a problem now. Using 
`julia version 1.6.2`
`Python 3.8.10`

when running the installation process, these lines fail:
https://github.com/sbi-benchmark/diffeqtorch/blob/f8b9285fae8e0088776ca892dbc1a6e4e941cfd2/diffeqtorch/install.py#L75-L80

```bash
...
Build Julia system image                                                                                                                                                                                           Traceback (most recent call last):                                                                                                                                                                                   File "<string>", line 1, in <module>                                                                                                                                                                               File "/home/ben/loc/lib/python3.8/site-packages/diffeqtorch/install.py", line 29, in install_and_test                                                                                               install_julia_sysimage()                                                                                                                                                                                         File "/home/ben/loc/lib/python3.8/site-packages/diffeqtorch/install.py", line 75, in install_julia_sysimage                                                                                         output = subprocess.run(                                                                                                                                                                                         File "/home/ben/loc/lib/python3.8/subprocess.py", line 516, in run                                                                                                                                  raise CalledProcessError(retcode, process.args,                                                                                                                                                                subprocess.CalledProcessError: Command 'julia --project=/home/ben/loc/lib/python3.8/site-packages/diffeqtorch/julia /home/ben/loc/lib/python3.8/site-packages/diffeqtorch/julia/sysimage.jl' returned non-zero exit status 1.
```

I shortened the path, but the error should still make sense. I ran the command myself:
`julia --project=/home/ben/loc/lib/python3.8/site-packages/diffeqtorch/julia /home/ben/loc/lib/python3.8/site-packages/diffeqtorch/julia/sysimage.jl`

I got the following output from `julia`:
```
Build system image
ERROR: LoadError: UndefVarError: create_sysimage not defined
Stacktrace:
[1] main()
@ Main ~/loc/lib/python3.8/site-packages/diffeqtorch/julia/sysimage.jl:32
[2] top-level scope
@ ~/loc/lib/python3.8/site-packages/diffeqtorch/julia/sysimage.jl:37
in expression starting at /home/ben/loc/lib/python3.8/site-packages/diffeqtorch/julia/sysimage.jl:37
```

**Comment by bkmi** [comment]
Hmm, it seems that installing `diffeqtorch` as a submodule in `pip -e` mode allowed for it to work... I also manually added the dependency of 
```julia
import Pkg
Pkg.add("PackageCompiler")
```

It's odd though because if the `PackageCompiler` was not installed, there should have been a different error, namely an import error.

**Comment by jan-matthis** [comment]
Hi, thanks for reporting this! It is indeed a bit odd, I'd have expected that `PackageCompiler` gets installed since it is specified in [`Project.toml`](https://github.com/sbi-benchmark/diffeqtorch/blob/main/diffeqtorch/julia/Project.toml#L8) with [the correct UUID](https://github.com/JuliaLang/PackageCompiler.jl/blob/master/Project.toml#L2). I have not updated Julia to version 1.6 yet, my first suspicion is that it has to do with that. I'll update my version soon and see if I can reproduce it.

**Comment by jan-matthis** [comment]
I updated Julia 1.4 to Julia 1.6. I first ran into an issue with Julia's package registry, which I fixed brute-force by removing`~/.julia`. Unfortunately, I then encountered a segfault which is also described in an open issue here: https://github.com/JuliaPy/pyjulia/issues/437. I will wait for the upstream issue to be resolved.

My current understanding is that `diffeqtorch` requires Julia ≤1.5 (at least on macOS), and Python ≤3.8.

**Comment by rakhmaevao** [comment]
Same problem on Julia 1.7.0, Python 3.8, Ubuntu 20.04.
