### ISSUE TITLE
CalledProcessError when installing diffeqtorch

### ISSUE THREAD

**Issue by Silentmoonlight** [sbi-benchmark/diffeqtorch#6]
Using
julia version 1.7.2
Python 3.8.0
when I try to install diffeqtorch by using python -c "from diffeqtorch.install import install_and_test; install_and_test()",something is wrong
Test Julia dependencies
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zjh/anaconda/envs/py38/lib/python3.8/site-packages/diffeqtorch/install.py", line 25, in install_and_test
    test_julia_deps()
  File "/home/zjh/anaconda/envs/py38/lib/python3.8/site-packages/diffeqtorch/install.py", line 45, in test_julia_deps
    output = subprocess.run(
  File "/home/zjh/anaconda/envs/py38/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'export JULIA_PROJECT=/home/zjh/anaconda/envs/py38/lib/python3.8/site-packages/diffeqtorch/julia; julia -E 'using DifferentialEquations'' returned non-zero exit status 1.

I wonder how can I fix it.

**Comment by givasile** [comment]
Same problem here. Is there any update?
